<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class App extends \Reloday\Application\Models\AppExt {

    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->hasOne('id', 'Reloday\Gms\Models\Company', 'app_id', [
            'alias' => 'Company'
        ]);
        $this->hasMany('id', 'Reloday\Gms\Models\AppSetting', 'app_id' , [
            'alias' => 'AppSetting'
        ]);
    }
}