<?php

namespace Reloday\Gms\Models;

use Reloday\Application\Lib\CacheHelper;

class AssignmentBasic extends \Reloday\Application\Models\AssignmentBasicExt
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->belongsTo('home_country_id', 'Reloday\Gms\Models\Country', 'id', [
            'alias' => 'HomeCountry',
            'cache' => [
                'key' => 'COUNTRY_' . $this->getHomeCountryId(),
                'lifetime' => CacheHelper::__TIME_6_MONTHS
            ]
        ]);

        $this->belongsTo('id', 'Reloday\Gms\Models\Assignment', 'id', [
            'alias' => 'Assignment'
        ]);
    }

    /**
     * @param $customData
     * @param $assignmentModel
     */
    public function createSingleOne($customData, $assignmentModel)
    {
        if (!method_exists($assignmentModel, 'getId') || !is_object($assignmentModel)) {
            return ['success' => false];
        }
        $this->setData($customData);
        $this->setId($assignmentModel->getId());
        if ($assignmentModel->getHomeCity() != '') {
            $this->setHomeCity($assignmentModel->getHomeCity());
        }
        if ($assignmentModel->getHomeCountryId() > 0) {
            $this->setHomeCountryId($assignmentModel->getHomeCountryId());
        }
        if ($assignmentModel->getHomeCityGeonameid() > 0) {
            $this->setHomeCityGeonameid($assignmentModel->getHomeCityGeonameid());
        }

        return $this->__quickCreate();
    }

    /**
     * @param $customData
     * @param $assignmentModel
     */
    public function updateSingleOne($customData, $assignmentModel)
    {
        if (!method_exists($assignmentModel, 'getId') || !is_object($assignmentModel)) {
            return ['success' => false];
        }
        if ($assignmentModel->getId() != $this->getId()) {
            return ['success' => false];
        }

        $this->setData($customData);

        if ($assignmentModel->getHomeCity() != '') {
            $this->setHomeCity($assignmentModel->getHomeCity());
        }
        if ($assignmentModel->getHomeCountryId() > 0) {
            $this->setHomeCountryId($assignmentModel->getHomeCountryId());
        }
        if ($assignmentModel->getHomeCityGeonameid() > 0) {
            $this->setHomeCityGeonameid($assignmentModel->getHomeCityGeonameid());
        }

        return $this->__quickUpdate();
    }
}
