<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

use PhpParser\Node\Expr\AssignOp\Mod;

class CompanyPricelist extends \Reloday\Application\Models\CompanyPricelistExt
{

    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->belongsTo('company_id', 'Reloday\Gms\Models\Company', 'id', [
            'alias' => 'Company',
        ]);

        $this->belongsTo('company_related_id', 'Reloday\Gms\Models\Company', 'id', [
            'alias' => 'CompanyRelated',
        ]);
        $this->hasMany('id', 'Reloday\Gms\Models\CompanyPricelistService', 'company_pricelist_id', [
            'alias' => 'CompanyPriceServices',
        ]);

        $this->hasManyToMany('id', 'Reloday\Gms\Models\CompanyPricelistService',
            'company_pricelist_id', 'service_price_id',
            'Reloday\Gms\Models\ServicePricing', 'id', [
                'alias' => 'ServicePricing',
            ]);
    }

    /**
     * @return bool
     */
    public function belongsToGms()
    {
        return ($this->getCompanyId() == ModuleModel::$company->getId());
    }
}