<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class CompanyFinancialDetail extends \Reloday\Application\Models\CompanyFinancialDetailExt
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->belongsTo('invoicing_city_geonameid', 'Reloday\Gms\Models\City', 'geonameid', ['alias' => 'City']);
    }

}
