<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class CompanyPricelistService extends \Reloday\Application\Models\CompanyPricelistServiceExt
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->belongsTo('service_price_id','Reloday\Gms\Models\ServicePricing','id',[
            'alias' => 'ServicePricing',
        ]);
    }
}