<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class HousingProposals extends \Reloday\Application\Models\HousingProposalsExt {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->hasMany('id', 'Reloday\Gms\Models\HousingProposalsN','housing_proposal_id',[
            'alias' => 'HousingProposalsItems',
        ]);


        $this->hasManyToMany('id', 'Reloday\Gms\Models\HousingProposalsN','housing_proposal_id',
            'id','Reloday\Gms\Models\HousingProposalDetail','housing_proposal_n_id',[
            'alias' => 'HousingProposalDetail',
        ]);
    }
}