<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class NeedAssessments extends \Reloday\Application\Models\NeedAssessmentsExt {

    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->hasMany('id','\Reloday\Gms\Models\NeedAssessmentItems','need_assessment_id', ['alias' => 'NeedAssessmentItems'] );
    }
}