<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class ServicePackHasService extends \Reloday\Application\Models\ServicePackHasServiceExt {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->belongsTo('service_company_id', 'Reloday\Gms\Models\ServiceCompany', 'id', [
            'alias' => 'ServiceCompany'
        ]);

        $this->belongsTo('service_pack_id', 'Reloday\Gms\Models\ServicePack', 'id', [
            'alias' => 'ServicePack'
        ]);
    }
}