<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

use Reloday\Application\Lib\CacheHelper;

class ServiceCompanyHasServiceProvider extends \Reloday\Application\Models\ServiceCompanyHasServiceProviderExt
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->belongsTo('service_provider_company_id', 'Reloday\Gms\Models\ServiceProviderCompany', 'id', [
            'alias' => 'ServiceProviderCompany',
        ]);

        $this->belongsTo('service_company_id', 'Reloday\Gms\Models\ServiceCompany', 'id', [
            'alias' => 'ServiceCompany',
            'cache' => [
                'key' => 'SERVICE_COMPANY_' . $this->getServiceCompanyId(),
                'lifetime' => CacheHelper::__TIME_6_MONTHS
            ],
        ]);
    }

    /**
     * @return bool
     */
    public function belongsToGms()
    {
        return $this->getServiceProviderCompany() && $this->getServiceProviderCompany()->belongsToGms()
            && $this->getServiceCompany() && $this->getServiceCompany()->belongsToGms();
    }
}