<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class ServiceProviderBusinessDetail extends \Reloday\Application\Models\ServiceProviderBusinessDetailExt
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->belongsTo('account_manager_user_profile_id','Reloday\Gms\Models\SvpMembers','id', [
            'alias' => 'AccountManager'
        ]);

        $this->belongsTo('head_office_user_profile_id','Reloday\Gms\Models\SvpMembers','id', [
            'alias' => 'HeadOffice'
        ]);
    }
}