<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class ServiceProviderFinancialDetails extends \Reloday\Application\Models\ServiceProviderFinancialDetailsExt
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->belongsTo('creditor_country_id','Reloday\Gms\Models\Country','id', ['alias' => 'CreditorCountry']);
    }
}