<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class ServiceProviderType extends \Reloday\Application\Models\ServiceProviderTypeExt {

    /**
     * set initialize
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->hasManyToMany('id', 'Reloday\Gms\Models\ServiceProviderCompanyHasServiceProviderType','service_provider_type_id',
            'service_provider_company_id','Reloday\Gms\Models\ServiceProviderCompany', 'id',[
                'alias' => 'ServiceProviderCompany',
                'params' => [
                    'distinct' => true,
                ]
            ]
        );
    }
}