<?php
/**
 * Created by PhpStorm.
 * User: binhnt
 * Date: 12/12/14
 * Time: 2:04 PM
 */

namespace Reloday\Gms\Models;

class TaxRule extends \Reloday\Application\Models\TaxRuleExt
{

    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->belongsTo('country_id', 'Reloday\Gms\Models\Country', 'id', [
            'alias' => 'Country'
        ]);
    }

    /**
     * @param $id
     */
    public static function __getActiveRateById($id)
    {
        $taxRule = self::findFirstById($id);
        if ($taxRule && $taxRule->belongsToGms() && $taxRule->isDeleted() == false) {
            return floatval($taxRule->getRate());
        }
    }

    /**
     * @return bool
     */
    public function belongsToGms()
    {
        return $this->getCompanyId() == ModuleModel::$company->getId();
    }

    public function isEditable()
    {
        $checkProductIfExist = ProductPricing::findFirstByTaxRuleId($this->getId());
        if ($checkProductIfExist instanceof ProductPricing) {
            return false;
        }
        $checkProductIfExist = AccountProductPricing::findFirstByTaxRuleId($this->getId());
        if ($checkProductIfExist instanceof AccountProductPricing) {
            return false;
        }
        $checkExpenseIfExist = Expense::findFirstByTaxRuleId($this->getId());
        if ($checkExpenseIfExist instanceof Expense) {
            return false;
        }
        $checkInvoiceItemIfExist = InvoiceQuoteItem::findFirstByTaxRuleId($this->getId());
        if ($checkInvoiceItemIfExist instanceof InvoiceQuoteItem) {
            return false;
        }
        return true;
    }
}
