<?php
/**
 * Do not edit this file manually, generated by the Yeoman Phalcon generator
 * Register application modules for the Reloday project
 */
return [

    'app' => [
        'className' => '\SMXD\App\Module',
        'path' => __DIR__ . '/../modules/app/Module.php',
    ],

    'api' => [
        'className' => '\SMXD\Api\Module',
        'path' => __DIR__ . '/../modules/api/Module.php',
    ]
];











