api-preprod.sanmayxaydung.com:
  hostname: 54.255.190.252
  user: centos
  pemFile: ../.configuration/pem/sanmayxaydung_preprod.pem
  pem_file: ../.configuration/pem/sanmayxaydung_preprod.pem
  identityFile: ../.configuration/pem/sanmayxaydung_preprod.pem
  forwardAgent: true
  multiplexing: true
  stage: dev
  roles:
      - app
      - db
  branch: thinhdev
  deploy_path: /home/smxd



