<?php
/**
 * List of 217 language codes: ISO 639-1.
 *
 * @author    Josantonius <hello@josantonius.com>
 * @copyright 2017 - 2018 (c) Josantonius - PHP-LanguageCode
 * @license   https://opensource.org/licenses/MIT - The MIT License (MIT)
 * @link      https://github.com/Josantonius/PHP-LanguageCode
 * @since     1.1.4
 */
namespace SMXD\Application\Lib;

/**
 * Language code handler.
 *
 * Compiled from https://wikipedia.org/wiki/List_of_ISO_639-1_codes
 */
class LanguageCodeCollection
{
    /**
     * List of language codes.
     *
     * @var array
     */
    protected static $data = [
        'aa' => 'Afar',
        'ab' => 'Abkhazian',
        'af' => 'Afrikaans',
        'am' => 'Amharic',
        'ar' => 'Arabic',
        'as' => 'Assamese',
        'ay' => 'Aymara',
        'az' => 'Azeri',
        'ba' => 'Bashkir',
        'be' => 'Belarusian',
        'bg' => 'Bulgarian',
        'bh' => 'Bihari',
        'bi' => 'Bislama',
        'bn' => 'Bengali',
        'bo' => 'Tibetan',
        'ca' => 'Catalan',
        'cs' => 'Czech',
        'cy' => 'Welsh',
        'da' => 'Danish',
        'de' => 'German',
        'div' => 'Divehi',
        'dz' => 'Bhutani',
        'el' => 'Greek',
        'en' => 'English',
        'es' => 'Spanish',
        'et' => 'Estonian',
        'eu' => 'Basque',
        'fa' => 'Farsi',
        'fi' => 'Finnish',
        'fj' => 'Fiji',
        'fo' => 'Faeroese',
        'fr' => 'French',
        'fy' => 'Frisian',
        'ga' => 'Irish',
        'gd' => 'Gaelic',
        'gl' => 'Galician',
        'gn' => 'Guarani',
        'gu' => 'Gujarati',
        'ha' => 'Hausa',
        'he' => 'Hebrew',
        'hi' => 'Hindi',
        'hr' => 'Croatian',
        'hu' => 'Hungarian',
        'hy' => 'Armenian',
        'id' => 'Indonesian',
        'ik' => 'Inupiak',
        'in' => 'Indonesian',
        'is' => 'Icelandic',
        'it' => 'Italian',
        'iw' => 'Hebrew',
        'ja' => 'Japanese',
        'ji' => 'Yiddish',
        'jw' => 'Javanese',
        'ka' => 'Georgian',
        'kk' => 'Kazakh',
        'km' => 'Cambodian',
        'kn' => 'Kannada',
        'ko' => 'Korean',
        'kok' => 'Konkani',
        'ks' => 'Kashmiri',
        'ku' => 'Kurdish',
        'ky' => 'Kirghiz',
        'kz' => 'Kyrgyz',
        'ln' => 'Lingala',
        'lo' => 'Laothian',
        'ls' => 'Slovenian',
        'lt' => 'Lithuanian',
        'lv' => 'Latvian',
        'mg' => 'Malagasy',
        'mi' => 'Maori',
        'mk' => 'FYRO Macedonian',
        'ml' => 'Malayalam',
        'mn' => 'Mongolian',
        'mo' => 'Moldavian',
        'mr' => 'Marathi',
        'ms' => 'Malay',
        'mt' => 'Maltese',
        'my' => 'Burmese',
        'na' => 'Nauru',
        'ne' => 'Nepali (India)',
        'nl' => 'Dutch',
        'nn-no' => 'Norwegian',
        'no' => 'Norwegian (Bokmal)',
        'om' => '(Afan)/Oromoor/Oriya',
        'or' => 'Oriya',
        'pa' => 'Punjabi',
        'pl' => 'Polish',
        'ps' => 'Pashto/Pushto',
        'pt' => 'Portuguese',
        'qu' => 'Quechua',
        'rn' => 'Kirundi',
        'ro' => 'Romanian',
        'ru' => 'Russian',
        'rw' => 'Kinyarwanda',
        'sa' => 'Sanskrit',
        'sb' => 'Sorbian',
        'sd' => 'Sindhi',
        'sg' => 'Sangro',
        'sh' => 'Serbo-Croatian',
        'si' => 'Singhalese',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'sm' => 'Samoan',
        'sn' => 'Shona',
        'so' => 'Somali',
        'sq' => 'Albanian',
        'sr' => 'Serbian',
        'ss' => 'Siswati',
        'st' => 'Sesotho',
        'su' => 'Sundanese',
        'sv' => 'Swedish',
        'sw' => 'Swahili',
        'sx' => 'Sutu',
        'syr' => 'Syriac',
        'ta' => 'Tamil',
        'te' => 'Telugu',
        'tg' => 'Tajik',
        'th' => 'Thai',
        'ti' => 'Tigrinya',
        'tk' => 'Turkmen',
        'tl' => 'Tagalog',
        'tn' => 'Tswana',
        'to' => 'Tonga',
        'tr' => 'Turkish',
        'ts' => 'Tsonga',
        'tt' => 'Tatar',
        'tw' => 'Twi',
        'uk' => 'Ukrainian',
        'ur' => 'Urdu',
        'uz' => 'Uzbek',
        'vi' => 'Vietnamese',
        'vo' => 'Volapuk',
        'wo' => 'Wolof',
        'xh' => 'Xhosa',
        'yi' => 'Yiddish',
        'yo' => 'Yoruba',
        'zh' => 'Chinese',
        'zu' => 'Zulu'
    ];

    protected static $dataTranslate = [
        'en' => [
            'aa' => 'Afar',
            'ab' => 'Abkhazian',
            'af' => 'Afrikaans',
            'am' => 'Amharic',
            'ar' => 'Arabic',
            'as' => 'Assamese',
            'ay' => 'Aymara',
            'az' => 'Azeri',
            'ba' => 'Bashkir',
            'be' => 'Belarusian',
            'bg' => 'Bulgarian',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengali',
            'bo' => 'Tibetan',
            'ca' => 'Catalan',
            'cs' => 'Czech',
            'cy' => 'Welsh',
            'da' => 'Danish',
            'de' => 'German',
            'div' => 'Divehi',
            'dz' => 'Bhutani',
            'el' => 'Greek',
            'en' => 'English',
            'es' => 'Spanish',
            'et' => 'Estonian',
            'eu' => 'Basque',
            'fa' => 'Farsi',
            'fi' => 'Finnish',
            'fj' => 'Fiji',
            'fo' => 'Faeroese',
            'fr' => 'French',
            'fy' => 'Frisian',
            'ga' => 'Irish',
            'gd' => 'Gaelic',
            'gl' => 'Galician',
            'gn' => 'Guarani',
            'gu' => 'Gujarati',
            'ha' => 'Hausa',
            'he' => 'Hebrew',
            'hi' => 'Hindi',
            'hr' => 'Croatian',
            'hu' => 'Hungarian',
            'hy' => 'Armenian',
            'id' => 'Indonesian',
            'ik' => 'Inupiak',
            'in' => 'Indonesian',
            'is' => 'Icelandic',
            'it' => 'Italian',
            'iw' => 'Hebrew',
            'ja' => 'Japanese',
            'ji' => 'Yiddish',
            'jw' => 'Javanese',
            'ka' => 'Georgian',
            'kk' => 'Kazakh',
            'km' => 'Cambodian',
            'kn' => 'Kannada',
            'ko' => 'Korean',
            'kok' => 'Konkani',
            'ks' => 'Kashmiri',
            'ku' => 'Kurdish',
            'ky' => 'Kirghiz',
            'kz' => 'Kyrgyz',
            'ln' => 'Lingala',
            'lo' => 'Laothian',
            'ls' => 'Slovenian',
            'lt' => 'Lithuanian',
            'lv' => 'Latvian',
            'mg' => 'Malagasy',
            'mi' => 'Maori',
            'mk' => 'FYRO Macedonian',
            'ml' => 'Malayalam',
            'mn' => 'Mongolian',
            'mo' => 'Moldavian',
            'mr' => 'Marathi',
            'ms' => 'Malay',
            'mt' => 'Maltese',
            'my' => 'Burmese',
            'na' => 'Nauru',
            'ne' => 'Nepali (India)',
            'nl' => 'Dutch',
            'nn-no' => 'Norwegian',
            'no' => 'Norwegian (Bokmal)',
            'om' => '(Afan)/Oromoor/Oriya',
            'or' => 'Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polish',
            'ps' => 'Pashto/Pushto',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'rn' => 'Kirundi',
            'ro' => 'Romanian',
            'ru' => 'Russian',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanskrit',
            'sb' => 'Sorbian',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-Croatian',
            'si' => 'Singhalese',
            'sk' => 'Slovak',
            'sl' => 'Slovenian',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somali',
            'sq' => 'Albanian',
            'sr' => 'Serbian',
            'ss' => 'Siswati',
            'st' => 'Sesotho',
            'su' => 'Sundanese',
            'sv' => 'Swedish',
            'sw' => 'Swahili',
            'sx' => 'Sutu',
            'syr' => 'Syriac',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'tg' => 'Tajik',
            'th' => 'Thai',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmen',
            'tl' => 'Tagalog',
            'tn' => 'Tswana',
            'to' => 'Tonga',
            'tr' => 'Turkish',
            'ts' => 'Tsonga',
            'tt' => 'Tatar',
            'tw' => 'Twi',
            'uk' => 'Ukrainian',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            'vi' => 'Vietnamese',
            'vo' => 'Volapuk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'zh' => 'Chinese',
            'zu' => 'Zulu'
        ],
        'es' => [
            'aa' => 'Afar',
            'ab' => 'Abjasio',
            'af' => 'Afrikáans',
            'am' => 'Amárico',
            'ar' => 'Árabe',
            'as' => 'Asamés',
            'ay' => 'Aymara',
            'az' => 'Azeri',
            'ba' => 'Baskires',
            'be' => 'Bielorruso',
            'bg' => 'Búlgaro',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengalí',
            'bo' => 'Tibetano',
            'ca' => 'Catalán',
            'cs' => 'Checo',
            'cy' => 'Galés',
            'da' => 'Danés',
            'de' => 'Alemán',
            'div' => 'Divhi',
            'dz' => 'Butani',
            'el' => 'Griego',
            'en' => 'Ingles',
            'es' => 'Español',
            'et' => 'Estonio',
            'eu' => 'Euskadi',
            'fa' => 'Farsi',
            'fi' => 'Finlandés',
            'fj' => 'Fiyi',
            'fo' => 'Feroés',
            'fr' => 'Francés',
            'fy' => 'Frisón',
            'ga' => 'Irlandés',
            'gd' => 'Gaélico',
            'gl' => 'Gallego',
            'gn' => 'Guaraní',
            'gu' => 'Gujaratí',
            'ha' => 'Hausa',
            'he' => 'Hebreo',
            'hi' => 'Hindi',
            'hr' => 'Croato',
            'hu' => 'Húngaro',
            'hy' => 'Armenio',
            'id' => 'Indonesio',
            'ik' => 'Inupiak',
            'in' => 'Indonesio',
            'is' => 'Islandés',
            'it' => 'Italiano',
            'iw' => 'Hebreo',
            'ja' => 'Japonés',
            'ji' => 'Yídish',
            'jw' => 'Javanés',
            'ka' => 'Georgiano',
            'kk' => 'Kazajo',
            'km' => 'Camboyano',
            'kn' => 'Kannada',
            'ko' => 'Coreano',
            'kok' => 'Konkani',
            'ks' => 'Cachemiro',
            'ku' => 'Kurdo',
            'ky' => 'Kirghuís',
            'kz' => 'Kyrguizo',
            'ln' => 'Lingala',
            'lo' => 'Laosiano',
            'ls' => 'Esloveno',
            'lt' => 'Lituano',
            'lv' => 'Letón',
            'mg' => 'Malgache',
            'mi' => 'Maorí',
            'mk' => 'Macedonio',
            'ml' => 'Malayalam',
            'mn' => 'Mongol',
            'mo' => 'Moldavo',
            'mr' => 'Marathi',
            'ms' => 'Malayo',
            'mt' => 'Maltés',
            'my' => 'Birmano',
            'na' => 'Nauru',
            'ne' => 'Nepalí',
            'nl' => 'Neerlandés',
            'nn-no' => 'Noruego',
            'no' => 'Noruego (Bokmal)',
            'om' => 'Afan/Oromoor/Oriya',
            'or' => 'Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polaco',
            'ps' => 'Pastún',
            'pt' => 'Portugués',
            'qu' => 'Quechua',
            'rn' => 'Kirundi',
            'ro' => 'Rumano',
            'ru' => 'Ruso',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sánscrito',
            'sb' => 'Sorabo',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-Croato',
            'si' => 'Cingalés',
            'sk' => 'Eslovaco',
            'sl' => 'Esloveno',
            'sm' => 'Samoano',
            'sn' => 'Shona',
            'so' => 'Somalí',
            'sq' => 'Albanés',
            'sr' => 'Serbio',
            'ss' => 'Sisvati',
            'st' => 'Sesotho',
            'su' => 'Sudanés',
            'sv' => 'Sueco',
            'sw' => 'Suajili',
            'sx' => 'Sutu',
            'syr' => 'Siríaco',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'tg' => 'Tayiko',
            'th' => 'Tailandés',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmeno',
            'tl' => 'Tagalo',
            'tn' => 'Tswana',
            'to' => 'Tonga',
            'tr' => 'Turco',
            'ts' => 'Tsonga',
            'tt' => 'Tártaro',
            'tw' => 'Twi',
            'uk' => 'Ucrainiano',
            'ur' => 'Urdu',
            'uz' => 'Uzbeko',
            'vi' => 'Vietnamita',
            'vo' => 'Volapuk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'zh' => 'Chino',
            'zu' => 'Zulú'
        ],
        'fr' => [
            'aa' => 'Afar',
            'ab' => 'Abkhaze',
            'af' => 'Afrikaans',
            'am' => 'Amharique',
            'ar' => 'Arabe',
            'as' => 'Assamais',
            'ay' => 'Aymara',
            'az' => 'Azère',
            'ba' => 'Bashkir',
            'be' => 'Bielorusse',
            'bg' => 'Bulgare',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengalais',
            'bo' => 'Tibetain',
            'ca' => 'Catalan',
            'cs' => 'Tchèque',
            'cy' => 'Galois',
            'da' => 'Danois',
            'de' => 'Allemand',
            'div' => 'Divehi',
            'dz' => 'Bhutanais',
            'el' => 'Grècque',
            'en' => 'Anglais',
            'es' => 'Espagnol',
            'et' => 'Estonien',
            'eu' => 'Basque',
            'fa' => 'Farsi',
            'fi' => 'Finlandais',
            'fj' => 'Fidjien',
            'fo' => 'Faeroais',
            'fr' => 'Français',
            'fy' => 'Frison',
            'ga' => 'Irlandais',
            'gd' => 'Gaelique',
            'gl' => 'Galitien',
            'gn' => 'Guarani',
            'gu' => 'Gujarati',
            'ha' => 'Hausa',
            'he' => 'Hebreu',
            'hi' => 'Hindi',
            'hr' => 'Croate',
            'hu' => 'Hongrois',
            'hy' => 'Armenien',
            'id' => 'Indonesien',
            'ik' => 'Inupiak',
            'in' => 'Indonesien',
            'is' => 'Islandais',
            'it' => 'Italien',
            'iw' => 'Hebreu',
            'ja' => 'Japonais',
            'ji' => 'Yiddish',
            'jw' => 'Javanais',
            'ka' => 'Georgien',
            'kk' => 'Kazaque',
            'km' => 'Cambodgien',
            'kn' => 'Kannada',
            'ko' => 'Coréen',
            'kok' => 'Konkani',
            'ks' => 'Kashmir',
            'ku' => 'Curde',
            'ky' => 'Kirguize',
            'kz' => 'Kirguize',
            'ln' => 'Lingala',
            'lo' => 'Laotien',
            'ls' => 'Slovène',
            'lt' => 'Lithuanien',
            'lv' => 'Letton',
            'mg' => 'Malgache',
            'mi' => 'Maori',
            'mk' => 'Macedonien',
            'ml' => 'Malayalam',
            'mn' => 'Mongole',
            'mo' => 'Moldave',
            'mr' => 'Marathi',
            'ms' => 'Malais',
            'mt' => 'Maltais',
            'my' => 'Birmain',
            'na' => 'Nauru',
            'ne' => 'Nepalais',
            'nl' => 'Hollandais',
            'nn-no' => 'Norvegien',
            'no' => 'Norvegien (Bokmal)',
            'om' => '(Afan)/Oromoor/Oriya',
            'or' => 'Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polonais',
            'ps' => 'Pachtoun',
            'pt' => 'Portugais',
            'qu' => 'Quechua',
            'rn' => 'Kirundi',
            'ro' => 'Roumain',
            'ru' => 'Russe',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanscrite',
            'sb' => 'Sorabo',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-Croate',
            'si' => 'Singalais',
            'sk' => 'Slovaque',
            'sl' => 'Slovène',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somalien',
            'sq' => 'Albanais',
            'sr' => 'Serbe',
            'ss' => 'Siswati',
            'st' => 'Sesotho',
            'su' => 'Sudanais',
            'sv' => 'Suedois',
            'sw' => 'Swahili',
            'sx' => 'Sutu',
            'syr' => 'Syriaque',
            'ta' => 'Tamil',
            'te' => 'Telougou',
            'tg' => 'Tajique',
            'th' => 'Thailandais',
            'ti' => 'Tigrine',
            'tk' => 'Turkmène',
            'tl' => 'Tagalogue',
            'tn' => 'Tswana',
            'to' => 'Tongais',
            'tr' => 'Turque',
            'ts' => 'Tsonga',
            'tt' => 'Tatare',
            'tw' => 'Twi',
            'uk' => 'Ukrainien',
            'ur' => 'Ourdou',
            'uz' => 'Uzbek',
            'vi' => 'Vietnamien',
            'vo' => 'Volapouk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'zh' => 'Chinois',
            'zu' => 'Zoulou'
        ],
        'it' => [
            'aa' => 'Afar',
            'ab' => 'Abcazio',
            'af' => 'Afrikaans',
            'am' => 'Amarico',
            'ar' => 'Arabo',
            'as' => 'Assamese',
            'ay' => 'Aymara',
            'az' => 'Azero',
            'ba' => 'Baskir',
            'be' => 'Bielorusso',
            'bg' => 'Bulgaro',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengalese',
            'bo' => 'Tibetano',
            'ca' => 'Catalano',
            'cs' => 'Ceco',
            'cy' => 'Gallese',
            'da' => 'Danese',
            'de' => 'Tedesco',
            'div' => 'Divehi',
            'dz' => 'Butanese',
            'el' => 'Greco',
            'en' => 'Inglese',
            'es' => 'Spagnolo',
            'et' => 'Estone',
            'eu' => 'Basco',
            'fa' => 'Farsi',
            'fi' => 'Finlandese',
            'fj' => 'Fidjano',
            'fo' => 'Faroese',
            'fr' => 'Francese',
            'fy' => 'Frisone',
            'ga' => 'Irlandese',
            'gd' => 'Gaelico',
            'gl' => 'Galiziano',
            'gn' => 'Guarani',
            'gu' => 'Gujaratíi',
            'ha' => 'Hausa',
            'he' => 'Ebraico',
            'hi' => 'Hindi',
            'hr' => 'Croato',
            'hu' => 'Ungherese',
            'hy' => 'Armeno',
            'id' => 'Indonesiano',
            'ik' => 'Inupiak',
            'in' => 'Indonesiano',
            'is' => 'Islandese',
            'it' => 'Italiano',
            'iw' => 'Ebraico',
            'ja' => 'Giapponese',
            'ji' => 'Yíddish',
            'jw' => 'Javanese',
            'ka' => 'Georgiano',
            'kk' => 'Kazako',
            'km' => 'Cambogiano',
            'kn' => 'Kannada',
            'ko' => 'Coreano',
            'kok' => 'Konkani',
            'ks' => 'Cachemir',
            'ku' => 'Curdo',
            'ky' => 'Kirghizo',
            'kz' => 'Kyrghizo',
            'ln' => 'Lingala',
            'lo' => 'Laotiano',
            'ls' => 'Sloveno',
            'lt' => 'Lituano',
            'lv' => 'Lettone',
            'mg' => 'Malgascio',
            'mi' => 'Maorí',
            'mk' => 'Macedone',
            'ml' => 'Malayam',
            'mn' => 'Mongolo',
            'mo' => 'Moldavo',
            'mr' => 'Marathi',
            'ms' => 'Malese',
            'mt' => 'Maltese',
            'my' => 'Birmano',
            'na' => 'Nauru',
            'ne' => 'Nepalese',
            'nl' => 'Olandese',
            'nn-no' => 'Norvegese',
            'no' => 'Norvegese (Bokmal)',
            'om' => 'Afan/Oromoor/Oriya',
            'or' => 'Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polacco',
            'ps' => 'Pashtun',
            'pt' => 'Portoghese',
            'qu' => 'Quechua',
            'rn' => 'Kirundi',
            'ro' => 'Rumeno',
            'ru' => 'Russo',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanscrito',
            'sb' => 'Sorabo',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-Croato',
            'si' => 'Cingalese',
            'sk' => 'Slovacco',
            'sl' => 'Sloveno',
            'sm' => 'Samoano',
            'sn' => 'Shona',
            'so' => 'Somalo',
            'sq' => 'Albanese',
            'sr' => 'Serbo',
            'ss' => 'Sisvati',
            'st' => 'Sesotho',
            'su' => 'Sudanese',
            'sv' => 'Svedese',
            'sw' => 'Suajili',
            'sx' => 'Sutu',
            'syr' => 'Siriaco',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'tg' => 'Tagiko',
            'th' => 'Tailandese',
            'ti' => 'Tigrino',
            'tk' => 'Turkmeno',
            'tl' => 'Tagalog',
            'tn' => 'Tswana',
            'to' => 'Tonga',
            'tr' => 'Turco',
            'ts' => 'Tsonga',
            'tt' => 'Tartaro',
            'tw' => 'Twi',
            'uk' => 'Ucraino',
            'ur' => 'Urdu',
            'uz' => 'Uzbeko',
            'vi' => 'Vietnamita',
            'vo' => 'Volapuk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'zh' => 'Cinese',
            'zu' => 'Zulu'
        ],
    ];

    /**
     * Returns all language codes.
     *
     * @return array
     */
    public static function all()
    {
        return static::$data;
    }

    /**
     * Returns all language codes translation.
     *
     * @return array
     */
    public static function getAllTranslate($language = 'en')
    {
        if(!$language || $language == null || $language == 'null'){
            $language = 'en';
        }

        $language = Helpers::__removeStringQuote($language);

        return static::$dataTranslate[$language];
    }

    /**
     * Return language name from language code.
     *
     * @param string $key
     *
     * @return string|null → language code or null
     */
    public static function get($key)
    {
        if (isset(static::$data[$key])) {
            return static::$data[$key];
        }

        return null;
    }

    /**
     * Return language name from language code.
     *
     * @param string $key
     *
     * @return string|null → language code or null
     */
    public static function getTranslateByKey($key, $lang = 'en')
    {
        if (isset(static::$dataTranslate[$lang][$key])) {
            return static::$dataTranslate[$lang][$key];
        }

        return null;
    }
}