<?php

return new \Phalcon\Config([
    'database' => [
        'adapter' => getenv('DB_ADAPTER'),
        'host' => getenv('DB_HOST'),
        'username' => getenv('DB_USERNAME'),
        'password' => getenv('DB_PASSWORD'),
        'dbname' => getenv('DB_DATABASE'),
        'port' => getenv('DB_PORT'),
        'persistent' => false,
        'charset' => 'utf8'
    ],

	'controllers' => [
		'annotationRouted' => [
			'\Reloday\Gms\Controllers\API\ServiceTemplate',
			'\Reloday\Gms\Controllers\API\ObjectTag',
			'\Reloday\Gms\Controllers\API\ExtractDataAssignee',
			'\Reloday\Gms\Controllers\API\ExtractDataAssignment',
			'\Reloday\Gms\Controllers\API\ExtractDataRelocation',
			'\Reloday\Gms\Controllers\API\ExtractDataService',
			'\Reloday\Gms\Controllers\API\EmployeeLogin',
			'\Reloday\Gms\Controllers\API\MemberLogin',
			'\Reloday\Gms\Controllers\API\AssigneeDocument',
			'\Reloday\Gms\Controllers\API\EmployeeDocument',
			'\Reloday\Gms\Controllers\API\Dependant',
			'\Reloday\Gms\Controllers\API\City',
			'\Reloday\Gms\Controllers\API\HrAccount',
			'\Reloday\Gms\Controllers\API\InvoiceTemplate',
			'\Reloday\Gms\Controllers\API\SupportContact',
			'\Reloday\Gms\Controllers\API\ContactMember',
			'\Reloday\Gms\Controllers\API\ObjectMapping',
			'\Reloday\Gms\Controllers\API\NotificationConfig',
			'\Reloday\Gms\Controllers\API\Guide',
			'\Reloday\Gms\Controllers\API\EntityDocument',
			'\Reloday\Gms\Controllers\API\Document',
			'\Reloday\Gms\Controllers\API\DataMember',
            '\Reloday\Gms\Controllers\API\CommunicationTemplate',
			'\Reloday\Gms\Controllers\API\MyCompany',
			'\Reloday\Gms\Controllers\API\MediaV1',
			'\Reloday\Gms\Controllers\API\AttachmentsV2',
			'\Reloday\Gms\Controllers\API\AttachmentsV1',
			'\Reloday\Gms\Controllers\API\UploaderV1',
			'\Reloday\Gms\Controllers\API\ExtractData',
			'\Reloday\Gms\Controllers\API\Bookers',
			'\Reloday\Gms\Controllers\API\Media',
			'\Reloday\Gms\Controllers\API\Communication',
			'\Reloday\Gms\Controllers\API\Needform',
			'\Reloday\Gms\Controllers\API\Login',
			'\Reloday\Gms\Controllers\API\Dashboard',
			'\Reloday\Gms\Controllers\API\Member',
			'\Reloday\Gms\Controllers\API\Report',
			'\Reloday\Gms\Controllers\API\Reminder',
			'\Reloday\Gms\Controllers\API\CustomerSupportTicket',
			'\Reloday\Gms\Controllers\API\Error',
			'\Reloday\Gms\Controllers\API\Faq',
			'\Reloday\Gms\Controllers\API\History',
			'\Reloday\Gms\Controllers\API\UserGuide',
			'\Reloday\Gms\Controllers\API\CompanyPriceList',
			'\Reloday\Gms\Controllers\API\MoveManagement',
			'\Reloday\Gms\Controllers\API\NeedAssessment',
			'\Reloday\Gms\Controllers\API\Notification',
			'\Reloday\Gms\Controllers\API\Participation',
			'\Reloday\Gms\Controllers\API\Servicenotification',
			'\Reloday\Gms\Controllers\API\Tasknotification',
			'\Reloday\Gms\Controllers\API\Taskhistory',
			'\Reloday\Gms\Controllers\API\Comments',
			'\Reloday\Gms\Controllers\API\Profile',
			'\Reloday\Gms\Controllers\API\Password',
			'\Reloday\Gms\Controllers\API\EmployeeInformation',
			'\Reloday\Gms\Controllers\API\Task',
			'\Reloday\Gms\Controllers\API\RelocationService',
			'\Reloday\Gms\Controllers\API\Test',
			'\Reloday\Gms\Controllers\API\Translate',
			'\Reloday\Gms\Controllers\API\HomeSearch',
			'\Reloday\Gms\Controllers\API\Contacts',
			'\Reloday\Gms\Controllers\API\Relocation',
			'\Reloday\Gms\Controllers\API\TaxRule',
			'\Reloday\Gms\Controllers\API\Property',
			'\Reloday\Gms\Controllers\API\Allowancetitle',
			'\Reloday\Gms\Controllers\API\Allowancetype',
			'\Reloday\Gms\Controllers\API\Attachments',
			'\Reloday\Gms\Controllers\API\Menu',
			'\Reloday\Gms\Controllers\API\Policy',
			'\Reloday\Gms\Controllers\API\Assignmenttypes',
			'\Reloday\Gms\Controllers\API\Assignmentlist',
			'\Reloday\Gms\Controllers\API\Attributes',
			'\Reloday\Gms\Controllers\API\Assignment',
			'\Reloday\Gms\Controllers\API\Property',
			'\Reloday\Gms\Controllers\API\ServicePack',
			'\Reloday\Gms\Controllers\API\Service',
			'\Reloday\Gms\Controllers\API\Setting',
			'\Reloday\Gms\Controllers\API\SvpCompany',
			'\Reloday\Gms\Controllers\API\GmsCompany',
			'\Reloday\Gms\Controllers\API\GmsMember',
			'\Reloday\Gms\Controllers\API\Role',
			'\Reloday\Gms\Controllers\API\SvpWorker',
			'\Reloday\Gms\Controllers\API\HrMember',
			'\Reloday\Gms\Controllers\API\Uploader',
            '\Reloday\Gms\Controllers\API\Employee',
            '\Reloday\Gms\Controllers\API\Company',
            '\Reloday\Gms\Controllers\API\Department',
            '\Reloday\Gms\Controllers\API\Office',
            '\Reloday\Gms\Controllers\API\Team',
            '\Reloday\Gms\Controllers\API\Acl',
            '\Reloday\Gms\Controllers\API\User',
            '\Reloday\Gms\Controllers\API\Auth',
            '\Reloday\Gms\Controllers\API\Index',
            '\Reloday\Gms\Controllers\API\SalaryCalculator',
		]
	],
	'application' => [
		'appType' => 'gms',
        'cachePrefix' => '_GMS',
	],
	'url_file' => __DIR__ . '/../../../../public', // if from another host, we can set http://www.site_name.domain_extension
]);
